version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    environment:
      PGADMIN_DEFAULT_EMAIL: test@user
      PGADMIN_DEFAULT_PASSWORD: PUg2rt6Pp8Arx7Z9FbgJLFvxEL7pZ2
    links:
      - postgres
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    restart: unless-stopped
volumes: 
  pgdata: